# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.marcusps.com
title: Your Awesome Site
email: marcusps1@gmail.com
author: Marcus Petty-Saphon
description: > I am a web developer based in London , come check out my work!

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/marcusps
  - title: github
    url: https://github.com/marcusps11
  - title: linkedin
    url: https://uk.linkedin.com/in/marcusps


